/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eventexposure

import (
	"github.com/nycu-ucr/gonet/http"

	"github.com/nycu-ucr/gin"
)

// SubscriptionsPost -
func SubscriptionsPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SubscriptionsSubIdDelete -
func SubscriptionsSubIdDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SubscriptionsSubIdGet -
func SubscriptionsSubIdGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SubscriptionsSubIdPut -
func SubscriptionsSubIdPut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
